#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME=$(basename "$0")
CURRENT_DIR_RELATIVE=$(dirname "$0")
CURRENT_DIR=$(cd "$CURRENT_DIR_RELATIVE" || exit;pwd)
#PARENT_DIR=$(cd "$CURRENT_DIR"/.. || exit;pwd)
#GRANDPARENT_DIR=$(cd "$PARENT_DIR"/.. || exit;pwd)

sudo docker run --rm -it -v $CURRENT_DIR:/src -p 1313:1313 klakegg/hugo:latest "$@"
suod chown -R $USER.$USER $CURRENT_DIR/contents
